AWSTemplateFormatVersion: '2010-09-09'
Description: CID Data Collection utilities for GitSync
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Deployment parameters'
        Parameters:
          - ManagementAccountGitSyncRoleName
          - ManagementAccountCfnRoleName      

Parameters:
  ManagementAccountGitSyncRoleName:
    Type: String
    Description: IAM role used by git-sync in the management account
    Default: CidGitSyncRole
  ManagementAccountCfnRoleName:
    Type: String
    Description: 'IAM role used by CloudFormation to deploy CID data collection resources in the management account'
    Default: CidCfnRole
      
Resources:
  ManagementAccountGitSyncRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ManagementAccountGitSyncRoleName}"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.sync.codeconnections.amazonaws.com 
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyName: CidGitSyncPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SyncToCloudFormation
                Effect: Allow
                Action: 
                -  cloudformation:CreateChangeSet
                -  cloudformation:DeleteChangeSet
                -  cloudformation:DescribeChangeSet
                -  cloudformation:DescribeStackEvents
                -  cloudformation:DescribeStacks
                -  cloudformation:ExecuteChangeSet
                -  cloudformation:GetTemplate
                -  cloudformation:ListChangeSets
                -  cloudformation:ListStacks
                -  cloudformation:ValidateTemplate
                Resource: "*"
              - Sid: PolicyForManagedRules
                Effect: Allow
                Action: 
                - events:PutRule
                - events:PutTargets
                Resource: "*"
                Condition: 
                  StringEquals: 
                    "events:ManagedBy": "cloudformation.sync.codeconnections.amazonaws.com"
              - Sid: PolicyForDescribingRule
                Effect: Allow
                Action: "events:DescribeRule"
                Resource: "*"
  ManagementAccountCfnRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ManagementAccountCfnRoleName}"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com 
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyName: DeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"















